import type { NewItem } from "@latestarr/adapter-core";
import Handlebars from "handlebars";
import mjml2html from "mjml";
import type { SourceButton } from "./source-buttons.js";

// Every design renders through here: MJML containing Handlebars tokens
// (e.g. {{#each items}}), whether generated from a design's options
// (design.ts) or written by hand in a code design. {{title}}/etc. use
// Handlebars' default {{}} escaping, not {{{}}}, so item text from a
// source can't inject markup into the compiled HTML.

interface RenderableItem {
  kind: string;
  title: string;
  subtitle?: string;
  overview?: string;
  addedAtFormatted: string;
  releaseDateFormatted?: string;
  posterUrl?: string;
  /** A short badge for the item. Adapter-set NewItem.contentLabel (e.g.
   * "Ebook" vs "Comic", or "Audiobook" vs "Podcast") takes priority when
   * present; otherwise this falls back to a label for item.kind itself
   * (see KIND_LABELS below), so every item gets some badge — Movie, TV
   * Episode, TV Season, Game, Book, or Audiobook. Always set. */
  contentLabel: string;
  genres?: string;
  rating?: string;
  runtimeFormatted?: string;
  pageCount?: number;
  durationFormatted?: string;
  platform?: string;
  /** Runtime, pages, length, or platform, then rating, joined with " · ";
   * absent when the item has none of them. */
  detailsLine?: string;
  /** The overview cut to about two lines, at a word, with an ellipsis. */
  overviewShort?: string;
  /** Set on a row standing in for several new episodes of one series
   * (mediaList's groupEpisodes): each episode's subtitle and link, up to
   * MAX_LISTED_EPISODES of them. */
  episodes?: { subtitle?: string; externalUrl?: string }[];
  /** How many episodes a grouped row stands for, and how many of those
   * aren't listed in `episodes`. */
  episodeCount?: number;
  moreEpisodes?: number;
  externalUrl?: string;
  /** Set only on an item substituted in by a Media List block's
   * emptyFallback="random" — lets a template's card markup mark it as a
   * suggestion rather than something newly added. */
  isFallback?: boolean;
}

export interface MjmlRenderContext {
  newsletterName: string;
  /** The "latest added" pool, used by a Media List block with sort="added". */
  items: NewItem[];
  /** The "most watched" pool, used by a Media List block with sort="mostWatched".
   * Empty when no linked source supports fetchPopularItems. */
  popularItems?: NewItem[];
  /** An all-time (not lookback-window-limited) pool a Media List block with
   * emptyFallback="random" samples from when its normal pool comes up
   * empty for the period — e.g. "no games added this week, here are 5 to
   * try". Only fetched by the caller when a compiled template actually
   * has such a block, so a newsletter that doesn't use it never pays for
   * the extra source calls. */
  fallbackItems?: NewItem[];
  /** Each content kind's linked source base URL, for a Media List block's
   * emptyFallback="link" — "browse the library yourself" when there's
   * nothing new to show. Keyed by NewItem["kind"]; a kind served by more
   * than one linked source resolves to whichever was resolved first. */
  sourceLinksByContentType?: Record<string, string>;
  generatedAt: Date;
  /** The newsletter's configured lookback-window length, for the default
   * template's "Here's what's new in the last N days" intro line
   * (design.ts). Bound as {{lookbackDays}} for code designs too. */
  lookbackDays?: number;
  /** Free-text shown near the top of the default template, above the item
   * list. Bound as {{introText}} for any template that references it. */
  introText?: string;
  /** Free-text shown near the bottom of the default template, above the
   * "Generated by LatestArr" line. Bound as {{footerNote}}. */
  footerNote?: string;
  /** Up to a handful of {label, url} call-to-action buttons the default
   * template renders as a row of buttons. Bound as {{#each ctas}} for any
   * template that references it. */
  ctas?: { label: string; url: string }[];
  /** "Watch on Plex"-style buttons, one per linked source with a public
   * URL (source-buttons.ts). Bound as {{#each sourceButtons}}, or
   * {{#sourceButtonsFor contentType="movie"}} for one section's. */
  sourceButtons?: SourceButton[];
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

// Shared by runtimeMinutes (movies/TV) and durationSeconds (audiobooks,
// converted to minutes first) so both land on the same "1h 45m" / "45m" shape.
function formatMinutes(totalMinutes: number): string {
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours === 0) return `${minutes}m`;
  if (minutes === 0) return `${hours}h`;
  return `${hours}h ${minutes}m`;
}

function formatRating(rating: NewItem["rating"]): string | undefined {
  if (!rating) return undefined;
  return `${rating.value}/${rating.scale}`;
}

// A display label for every MediaKind, used as the badge shown when an
// item has no adapter-set contentLabel (Plex/Tautulli/RomM movies, TV
// episodes/seasons and games never set one — only BookLore-family and
// Audiobookshelf do, to distinguish Ebook/Comic/Audiobook/Podcast within
// their shared "book"/"audiobook" kinds). Keeping this map here, and
// resolving it into contentLabel once in toRenderable below, means badge
// markup only ever has to read {{contentLabel}}: it never needs its own
// copy of this map or to know about `kind` at all.
const KIND_LABELS: Record<NewItem["kind"], string> = {
  movie: "Movie",
  tv_episode: "TV Episode",
  tv_season: "TV Season",
  game: "Game",
  book: "Book",
  audiobook: "Audiobook",
};

function resolveContentLabel(item: NewItem): string {
  return item.contentLabel ?? KIND_LABELS[item.kind];
}

// isFallback is never set here — the mediaList helper below is the only
// place that flags an item as a fallback suggestion, by spreading it onto
// an already-mapped RenderableItem once it's decided to use it that way.
function detailsLineOf(item: RenderableItem): string | undefined {
  const size = item.runtimeFormatted ?? (item.pageCount ? `${item.pageCount} pages` : undefined) ?? item.durationFormatted;
  const parts = [size, item.platform, item.rating].filter((part): part is string => Boolean(part));
  return parts.length > 0 ? parts.join(" · ") : undefined;
}

const OVERVIEW_SHORT_LENGTH = 180;

// Email clients don't support line-clamp, so "about two lines" is a
// character count, cut back to the last whole word.
function shorten(text: string | undefined): string | undefined {
  if (!text || text.length <= OVERVIEW_SHORT_LENGTH) return text;
  const cut = text.slice(0, OVERVIEW_SHORT_LENGTH);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > OVERVIEW_SHORT_LENGTH / 2 ? cut.slice(0, lastSpace) : cut).replace(/[\s,.;:–-]+$/, "")}…`;
}

function toRenderable(item: NewItem): RenderableItem {
  const renderable: RenderableItem = {
    kind: item.kind,
    title: item.title,
    subtitle: item.subtitle,
    overview: item.overview,
    addedAtFormatted: formatDate(item.addedAt),
    releaseDateFormatted: item.releaseDate ? formatDate(item.releaseDate) : undefined,
    // By the time this runs, a real send has already replaced this with a
    // `cid:...` reference (or dropped it) in apps/server/src/pipeline
    // /embed-images.ts — never a source's own (often credential-bearing)
    // URL. mjml-template.test.ts exercises this field directly with a
    // plain URL, which is fine for testing the template mechanics in
    // isolation.
    posterUrl: item.posterUrl,
    contentLabel: resolveContentLabel(item),
    genres: item.genres?.length ? item.genres.join(", ") : undefined,
    rating: formatRating(item.rating),
    runtimeFormatted: item.runtimeMinutes ? formatMinutes(item.runtimeMinutes) : undefined,
    pageCount: item.pageCount,
    durationFormatted: item.durationSeconds
      ? formatMinutes(Math.round(item.durationSeconds / 60))
      : undefined,
    platform: item.platform,
    externalUrl: item.externalUrl,
  };
  return { ...renderable, detailsLine: detailsLineOf(renderable), overviewShort: shorten(renderable.overview) };
}

// Fisher-Yates, used by the mediaList helper's order="random" variant and
// by its emptyFallback="random" substitute pool — a fresh shuffle on every
// render, not a stable/seeded one, since "random" here means "surprise me
// this send," not a reproducible order.
function shuffled<T>(items: T[]): T[] {
  const result = items.slice();
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j] as T, result[i] as T];
  }
  return result;
}

// The accent color of LatestArr's own Bloom palette (hsl(343 74% 44%)),
// matching the Default design; its only use is the emptyFallback="link"
// plain-link markup below.
const ACCENT_COLOR = "#c31d4c";

// Shared by the mediaList and ifAnyItems helpers below: which pool a given
// sort reads from, and whether an item matches a (possibly absent, meaning
// "no filter") contentType hash argument. Split out so ifAnyItems can ask
// "would mediaList render anything for this contentType/sort" without
// duplicating mediaList's own pool-selection/filter logic.
function selectPool(
  context: { items?: RenderableItem[]; popularItems?: RenderableItem[] },
  sort: string | undefined,
): RenderableItem[] {
  return sort === "mostWatched" ? (context.popularItems ?? []) : (context.items ?? []);
}

// contentType may name several kinds, comma-separated (e.g. a "TV"
// section showing "tv_episode,tv_season").
function matchesContentType(item: RenderableItem, contentType: string | undefined): boolean {
  return !contentType || contentType.split(",").includes(item.kind);
}

const MAX_LISTED_EPISODES = 5;

// Several new episodes of one series become a single row: the first
// episode's details (title, poster, link) with the rest listed beneath.
// Rows keep the order of each series' first appearance.
function groupEpisodes(items: RenderableItem[]): RenderableItem[] {
  const bySeries = new Map<string, RenderableItem[]>();
  for (const item of items) {
    if (item.kind !== "tv_episode") continue;
    bySeries.set(item.title, [...(bySeries.get(item.title) ?? []), item]);
  }
  const rows: RenderableItem[] = [];
  const done = new Set<string>();
  for (const item of items) {
    const series = item.kind === "tv_episode" ? bySeries.get(item.title) : undefined;
    if (!series || series.length < 2) {
      rows.push(item);
      continue;
    }
    if (done.has(item.title)) continue;
    done.add(item.title);
    rows.push({
      ...item,
      subtitle: undefined,
      overview: undefined,
      overviewShort: undefined,
      detailsLine: undefined,
      releaseDateFormatted: undefined,
      episodes: series.slice(0, MAX_LISTED_EPISODES).map((episode) => ({
        subtitle: episode.subtitle,
        externalUrl: episode.externalUrl,
      })),
      episodeCount: series.length,
      moreEpisodes: Math.max(0, series.length - MAX_LISTED_EPISODES),
    });
  }
  return rows;
}

// A filtered, sorted, trimmed list, configured by hash arguments —
// {{#mediaList contentType="movie" sort="added" count="5"
// order="sequential" showAll="false" emptyFallback="none"}}...{{/mediaList}}.
// The block body is rendered once per matching item, exactly like a
// filtered/sorted/sliced {{#each}}.
Handlebars.registerHelper("mediaList", function mediaList(
  this: {
    items?: RenderableItem[];
    popularItems?: RenderableItem[];
    fallbackItems?: RenderableItem[];
    sourceLinksByContentType?: Record<string, string>;
  },
  options: Handlebars.HelperOptions,
) {
  const { contentType, sort, count, order, showAll, emptyFallback, fallbackCount, fallbackLinkLabel, fallbackWrap, groupEpisodes: group } =
    options.hash as {
      contentType?: string;
      sort?: string;
      count?: number | string;
      order?: string;
      showAll?: boolean | string;
      emptyFallback?: string;
      fallbackCount?: number | string;
      fallbackLinkLabel?: string;
      /** "none" when the helper is already inside an <mj-raw> (design
       * output), so the fallback link mustn't add a second, nested one. */
      fallbackWrap?: string;
      /** "true" to fold several episodes of one series into one row. */
      groupEpisodes?: boolean | string;
    };

  const pool = selectPool(this, sort);
  let filtered = pool.filter((item) => matchesContentType(item, contentType));
  if (order === "random") filtered = shuffled(filtered);
  if (group === true || group === "true") filtered = groupEpisodes(filtered);

  const isShowAll = showAll === true || showAll === "true";
  const limit = Number(count);
  let selected = isShowAll
    ? filtered
    : filtered.slice(0, Number.isFinite(limit) && limit > 0 ? limit : filtered.length);

  if (selected.length === 0 && emptyFallback === "random") {
    const fallbackPool = (this.fallbackItems ?? []).filter((item) => matchesContentType(item, contentType));
    const fallbackLimit = Number(fallbackCount) || (Number.isFinite(limit) && limit > 0 ? limit : 5);
    selected = shuffled(fallbackPool)
      .slice(0, fallbackLimit)
      .map((item) => ({ ...item, isFallback: true }));
  }

  if (selected.length === 0 && emptyFallback === "link") {
    const href = contentType
      ?.split(",")
      .map((kind) => this.sourceLinksByContentType?.[kind])
      .find(Boolean);
    if (!href) return "";
    const label = Handlebars.escapeExpression(fallbackLinkLabel || "Browse the library");
    // Wrapped in its own <mj-raw> unless told otherwise: this string
    // substitutes directly into the MJML at the {{#mediaList}} site, often
    // straight inside an <mj-column>, where bare non-mj-tag HTML is
    // silently dropped.
    const link =
      `<a href="${Handlebars.escapeExpression(href)}" ` +
      `style="color:${ACCENT_COLOR};font-family:sans-serif;font-size:14px;font-weight:600;">` +
      `${label} &rarr;</a>`;
    return fallbackWrap === "none" ? link : `<mj-raw>${link}</mj-raw>`;
  }

  return selected.map((item) => options.fn(item)).join("");
});

// Lets a heading above a {{#mediaList}} disappear along with its (empty)
// list, rather than sitting above a blank section.
// {{#mediaList}} itself can't answer "would I render anything" from outside
// — it's a block helper whose body only ever runs once per matching item,
// with no count exposed to the surrounding template — so this is a second,
// read-only helper applying the exact same pool + contentType filter
// mediaList uses, purely to decide whether to render its block at all.
// Given the same contentType/sort as that {{#mediaList}}, "would mediaList
// render anything" and "is this filtered pool non-empty" are the same
// question.
Handlebars.registerHelper("ifAnyItems", function ifAnyItems(
  this: { items?: RenderableItem[]; popularItems?: RenderableItem[] },
  options: Handlebars.HelperOptions,
) {
  const { contentType, sort } = options.hash as { contentType?: string; sort?: string };
  const pool = selectPool(this, sort);
  const hasAny = pool.some((item) => matchesContentType(item, contentType));
  return hasAny ? options.fn(this) : options.inverse(this);
});

// The source buttons for sources providing any of these content types (a
// comma list), or all of them without one; the else block runs when none do.
Handlebars.registerHelper("sourceButtonsFor", function sourceButtonsFor(
  this: { sourceButtons?: SourceButton[] },
  options: Handlebars.HelperOptions,
) {
  const { contentType } = options.hash as { contentType?: string };
  const wanted = contentType?.split(",").map((kind) => kind.trim());
  const buttons = (this.sourceButtons ?? []).filter(
    (button) => !wanted || button.kinds.some((kind) => wanted.includes(kind)),
  );
  if (buttons.length === 0) return options.inverse(this);
  return buttons.map((button) => options.fn(button)).join("");
});

// True when one of the newsletter's linked sources provides this content
// type, so a design only shows a "Books" section (even an empty one) for a
// newsletter that actually has a book source. Also true whenever there are
// items of that type, so a section never hides real items.
Handlebars.registerHelper("ifKindLinked", function ifKindLinked(
  this: { sourceLinksByContentType?: Record<string, string>; items?: RenderableItem[] },
  options: Handlebars.HelperOptions,
) {
  const { contentType } = options.hash as { contentType?: string };
  const linked = Boolean(contentType?.split(",").some((kind) => this.sourceLinksByContentType?.[kind]));
  const hasItems = (this.items ?? []).some((item) => matchesContentType(item, contentType));
  return linked || hasItems ? options.fn(this) : options.inverse(this);
});

const KIND_COUNT_LABELS: Record<NewItem["kind"], [string, string]> = {
  movie: ["movie", "movies"],
  tv_episode: ["episode", "episodes"],
  tv_season: ["season", "seasons"],
  book: ["book", "books"],
  audiobook: ["audiobook", "audiobooks"],
  game: ["game", "games"],
};

// "23 episodes", "9 movies", ... largest first.
function kindCounts(items: NewItem[]): string[] {
  const counts = new Map<NewItem["kind"], number>();
  for (const item of items) counts.set(item.kind, (counts.get(item.kind) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([kind, n]) => `${n} ${KIND_COUNT_LABELS[kind][n === 1 ? 0 : 1]}`);
}

// "Sep 21 – 28, 2026", "Aug 30 – Sep 5, 2026", or across years in full.
function formatPeriod(end: Date, days: number): string {
  const start = new Date(end.getTime() - days * 24 * 60 * 60 * 1000);
  const month = (d: Date) => d.toLocaleDateString("en-US", { month: "short" });
  if (start.getFullYear() !== end.getFullYear()) {
    const full = (d: Date) => d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
    return `${full(start)} – ${full(end)}`;
  }
  const endPart = start.getMonth() === end.getMonth() ? `${end.getDate()}` : `${month(end)} ${end.getDate()}`;
  return `${month(start)} ${start.getDate()} – ${endPart}, ${end.getFullYear()}`;
}

export async function renderMjmlTemplate(
  mjmlSource: string,
  context: MjmlRenderContext,
): Promise<string> {
  const substitutedMjml = Handlebars.compile(mjmlSource)({
    newsletterName: context.newsletterName,
    items: context.items.map(toRenderable),
    popularItems: (context.popularItems ?? []).map(toRenderable),
    fallbackItems: (context.fallbackItems ?? []).map(toRenderable),
    sourceLinksByContentType: context.sourceLinksByContentType ?? {},
    hasLinkedSources: Object.keys(context.sourceLinksByContentType ?? {}).length > 0,
    generatedAtFormatted: formatDate(context.generatedAt),
    lookbackDays: context.lookbackDays,
    periodFormatted: context.lookbackDays ? formatPeriod(context.generatedAt, context.lookbackDays) : undefined,
    itemCount: context.items.length,
    kindCounts: kindCounts(context.items),
    introText: context.introText,
    footerNote: context.footerNote,
    ctas: context.ctas ?? [],
    sourceButtons: context.sourceButtons ?? [],
  });

  // A code design may be a bare fragment (just its section/column content,
  // no root element), which mjml2html rejects outright even under "soft"
  // validation. Wrap it so it still renders instead of failing the send.
  const wrappedMjml = /^\s*<mjml[\s>]/.test(substitutedMjml)
    ? substitutedMjml
    : `<mjml><mj-body>${substitutedMjml}</mj-body></mjml>`;

  // "soft" validation still returns best-effort HTML for a malformed
  // code design rather than aborting the send outright — a markup
  // mistake shouldn't take down a newsletter that otherwise has
  // real content to deliver.
  const { html } = await mjml2html(wrappedMjml, { validationLevel: "soft" });
  return html;
}
