import type { NewItem } from "@latestarr/adapter-core";
import { describe, expect, it } from "vitest";
import { renderDefaultNewsletterHtml } from "./newsletter-template.js";

function item(overrides: Partial<NewItem> = {}): NewItem {
  return {
    id: "1",
    externalId: "1",
    kind: "movie",
    title: "Some Movie",
    addedAt: new Date("2026-01-15T12:00:00Z"),
    ...overrides,
  };
}

describe("renderDefaultNewsletterHtml", () => {
  it("renders each item's title, subtitle, overview, and formatted date", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ subtitle: "A subtitle", overview: "An overview." })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain("Weekly Digest");
    expect(html).toContain("Some Movie");
    expect(html).toContain("A subtitle");
    expect(html).toContain("An overview.");
    expect(html).toContain("Added January 15, 2026");
    expect(html).toContain("Generated by LatestArr on January 20, 2026");
  });

  it("shows a fallback message when there are no items", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain("No new items in this period.");
  });

  it("omits the subtitle/overview blocks entirely when absent", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).not.toContain("undefined");
  });

  it("HTML-escapes item text so a malicious title can't inject markup", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ title: "<script>alert(1)</script>" })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("renders a poster image with mandatory alt text and a formatted runtime for a movie", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [
        item({
          title: "A Movie",
          posterUrl: "https://example.com/poster.jpg",
          runtimeMinutes: 105,
          rating: { source: "tmdb", value: 7.8, scale: 10 },
        }),
      ],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain('src="https://example.com/poster.jpg"');
    expect(html).toContain('alt="A Movie cover art"');
    expect(html).toContain("1h 45m");
    expect(html).toContain("7.8/10");
  });

  it("wraps the title and poster in a link when the item has an externalUrl", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [
        item({
          title: "A Movie",
          posterUrl: "https://example.com/poster.jpg",
          externalUrl: "https://plex.example.com/web/index.html#!/server/abc/details?key=%2Flibrary%2Fmetadata%2F1",
        }),
      ],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    // {{externalUrl}} uses Handlebars' default {{}} HTML-escaping (like
    // every other item field), which also escapes "=" as "&#x3D;" — so the
    // rendered href isn't a byte-for-byte copy of the source URL.
    const escapedHref =
      "https://plex.example.com/web/index.html#!/server/abc/details?key&#x3D;%2Flibrary%2Fmetadata%2F1";
    // The poster wraps in a plain <a>...<img/></a>; the title's <a> also
    // carries the "inherit the surrounding text color, no underline" style
    // so a title-as-link doesn't read as a default blue/underlined link.
    expect(html).toContain(`<a href="${escapedHref}"><img`);
    expect(html).toContain(
      `<a href="${escapedHref}" style="color:inherit;text-decoration:none;">A Movie</a>`,
    );
  });

  it("renders a plain (non-linked) title and poster when the item has no externalUrl", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ title: "No Link Movie", posterUrl: "https://example.com/poster.jpg" })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    // The footer's own GitHub/"Report an issue" links are always present,
    // so this checks the item's own title/poster markup specifically
    // rather than asserting no <a href= appears anywhere in the document.
    expect(html).toContain("No Link Movie");
    expect(html).not.toContain('<a href="https://example.com/poster.jpg"');
    expect(html).not.toContain(">No Link Movie</a>");
  });

  it("omits the poster image entirely when an item has no posterUrl", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ title: "No Poster Movie" })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    // The footer's own GitHub/"Report an issue" icons are always present,
    // so this checks specifically for a poster <img> (width="88", matching
    // the item card's own poster markup) rather than asserting no <img>
    // appears anywhere in the document.
    expect(html).not.toContain('width="88"');
    expect(html).toContain("No Poster Movie");
  });

  it("shows a book's page count and an audiobook's duration in the metadata line", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [
        item({ id: "2", externalId: "2", kind: "book", title: "A Book", pageCount: 320 }),
        item({
          id: "3",
          externalId: "3",
          kind: "audiobook",
          title: "An Audiobook",
          durationSeconds: 5400,
        }),
      ],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain("320 pages");
    expect(html).toContain("1h 30m");
  });

  it("shows a contentLabel badge next to the title when present", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ kind: "book", title: "Some Comic", contentLabel: "Comic" })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain("Comic");
  });

  it("omits the contentLabel badge entirely when absent", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).not.toContain("undefined");
  });

  it("shows both the added date and a formatted release date when present", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ releaseDate: new Date("2020-05-01T12:00:00Z") })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain("Added January 15, 2026");
    expect(html).toContain("Released May 1, 2020");
  });

  it("does not fall back to the old bare list markup", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).not.toContain("<ul ");
    expect(html).not.toContain("<ul>");
    expect(html).not.toContain("<li>");
    expect(html).toContain("<!doctype html");
  });

  it("falls back to a kind-based badge (e.g. \"Movie\") when an item has no contentLabel", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ kind: "movie" })],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain(">Movie<");
  });

  it("shows a plain-language intro line naming the lookback window when lookbackDays is given", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
      lookbackDays: 14,
    });

    expect(html).toContain("Here's what's new in the last 14 days.");
  });

  it("omits the intro line entirely when lookbackDays is not given", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).not.toContain("Here's what's new");
  });

  it("includes a GitHub link and an issue-reporting link in the footer", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T12:00:00Z"),
    });

    expect(html).toContain('href="https://github.com/jshields-ca/LatestArr"');
    expect(html).toContain('href="https://github.com/jshields-ca/LatestArr/issues"');
    expect(html).toContain("Report an issue");
  });

  describe("emailFont", () => {
    it("defaults to the Ubuntu stack when emailFont is omitted", async () => {
      const html = await renderDefaultNewsletterHtml({
        newsletterName: "Weekly Digest",
        items: [item()],
        generatedAt: new Date("2026-01-20T12:00:00Z"),
      });

      expect(html).toContain("font-family:Ubuntu, Helvetica, Arial, sans-serif;");
    });

    it("renders with the requested font stack", async () => {
      const html = await renderDefaultNewsletterHtml({
        newsletterName: "Weekly Digest",
        items: [item()],
        generatedAt: new Date("2026-01-20T12:00:00Z"),
        emailFont: "georgia",
      });

      expect(html).toContain("font-family:Georgia, 'Times New Roman', serif;");
      expect(html).not.toContain("font-family:Ubuntu, Helvetica, Arial, sans-serif;");
    });

    it("falls back to the default font for an unrecognized emailFont value", async () => {
      const html = await renderDefaultNewsletterHtml({
        newsletterName: "Weekly Digest",
        items: [item()],
        generatedAt: new Date("2026-01-20T12:00:00Z"),
        emailFont: "comic-sans",
      });

      expect(html).toContain("font-family:Ubuntu, Helvetica, Arial, sans-serif;");
    });
  });
});
