import type { NewItem } from "@latestarr/adapter-core";
import { renderMjmlTemplate } from "./mjml-template.js";

// The "default layout" a newsletter falls back to when its Template dropdown
// has no custom template picked (or the picked template has no compiledMjml
// yet). This used to be a completely separate hand-rolled Handlebars/HTML
// template with no MJML compilation and no poster/metadata support — a
// second rendering pipeline duplicating everything mjml-template.ts already
// does properly. It's now just another MJML source rendered through the
// same renderMjmlTemplate() as a user-authored custom template, so both
// paths get responsive layout, MSO/Outlook conditionals, and poster +
// metadata cards for free. The header/footer sections mirror the markup
// GrapesJS's "Header"/"Footer" blocks export (apps/web/src/lib/grapesjs-blocks.ts)
// so a default-rendered email looks consistent with a GrapesJS-authored one,
// and the per-item card mirrors that file's Media List block toHTML() output.
// A plain {{#each items}} is used instead of the {{#mediaList}} block helper
// since there's no user-configurable content-type/sort/count filtering here
// — the default template just shows everything the pipeline already fetched,
// in the order given.
//
// The card content is plain HTML (a <table>/<img>/<div> layout), so per
// mjml-template.test.ts's CARD_MJML fixture it must live inside <mj-raw> —
// mjml2html silently strips raw non-mj-tag HTML that isn't wrapped in
// <mj-raw>.

// The accent color of LatestArr's own Bloom palette (hsl(343 74% 44%)),
// hardcoded here (as it is in grapesjs-blocks.ts) rather than imported from
// the Tailwind theme because this HTML ends up in a sent email, entirely
// outside the app's own CSS.
const ACCENT_COLOR = "#c31d4c";

const DEFAULT_MJML_TEMPLATE = `
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="24px" font-weight="600">{{newsletterName}}</mj-text>
      </mj-column>
    </mj-section>
    {{#if items.length}}
    <mj-section>
      <mj-column>
        <mj-raw>
        {{#each items}}
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;">
        <tr>
        {{#if posterUrl}}<td width="80" style="vertical-align:top;padding-right:12px;">{{#if externalUrl}}<a href="{{externalUrl}}">{{/if}}<img src="{{posterUrl}}" width="80" alt="{{title}} cover art" style="display:block;width:80px;max-width:80px;border-radius:6px;" />{{#if externalUrl}}</a>{{/if}}</td>{{/if}}
        <td style="vertical-align:top;font-family:sans-serif;">
          <div style="font-weight:600;font-size:16px;color:#0f172a;">{{#if externalUrl}}<a href="{{externalUrl}}" style="color:inherit;text-decoration:none;">{{title}}</a>{{else}}{{title}}{{/if}}{{#if contentLabel}} <span style="display:inline-block;font-size:10px;font-weight:600;color:${ACCENT_COLOR};border:1px solid ${ACCENT_COLOR};border-radius:4px;padding:1px 5px;vertical-align:middle;">{{contentLabel}}</span>{{/if}}</div>
          {{#if subtitle}}<div style="color:#64748b;font-size:13px;">{{subtitle}}</div>{{/if}}
          <div style="font-size:12px;font-weight:600;color:${ACCENT_COLOR};margin-top:2px;">{{#if runtimeFormatted}}{{runtimeFormatted}}{{/if}}{{#if pageCount}}{{pageCount}} pages{{/if}}{{#if durationFormatted}}{{durationFormatted}}{{/if}}{{#if platform}}{{platform}}{{/if}}{{#if rating}} · {{rating}}{{/if}}</div>
          {{#if overview}}<div style="font-size:13px;color:#334155;margin-top:4px;">{{overview}}</div>{{/if}}
          <div style="font-size:11px;color:#94a3b8;margin-top:4px;">Added {{addedAtFormatted}}{{#if releaseDateFormatted}} · Released {{releaseDateFormatted}}{{/if}}</div>
        </td>
        </tr>
        </table>
        {{/each}}
        </mj-raw>
      </mj-column>
    </mj-section>
    {{else}}
    <mj-section>
      <mj-column>
        <mj-text>No new items in this period.</mj-text>
      </mj-column>
    </mj-section>
    {{/if}}
    <mj-section>
      <mj-column>
        <mj-text font-size="12px" color="#999999">Generated by LatestArr on {{generatedAtFormatted}}</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
`;

export interface NewsletterRenderContext {
  newsletterName: string;
  items: NewItem[];
  generatedAt: Date;
}

export function renderDefaultNewsletterHtml(context: NewsletterRenderContext): Promise<string> {
  return renderMjmlTemplate(DEFAULT_MJML_TEMPLATE, {
    newsletterName: context.newsletterName,
    items: context.items,
    generatedAt: context.generatedAt,
  });
}
