import type { NewItem } from "@latestarr/adapter-core";
import { describe, expect, it } from "vitest";
import { renderDefaultNewsletterHtml } from "./newsletter-template.js";

function item(overrides: Partial<NewItem> = {}): NewItem {
  return {
    id: "1",
    externalId: "1",
    kind: "movie",
    title: "Some Movie",
    addedAt: new Date("2026-01-15T00:00:00Z"),
    ...overrides,
  };
}

describe("renderDefaultNewsletterHtml", () => {
  it("renders each item's title, subtitle, overview, and formatted date", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ subtitle: "A subtitle", overview: "An overview." })],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).toContain("Weekly Digest");
    expect(html).toContain("Some Movie");
    expect(html).toContain("A subtitle");
    expect(html).toContain("An overview.");
    expect(html).toContain("Added January 15, 2026");
    expect(html).toContain("Generated by LatestArr on January 20, 2026");
  });

  it("shows a fallback message when there are no items", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).toContain("No new items in this period.");
  });

  it("omits the subtitle/overview blocks entirely when absent", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).not.toContain("undefined");
  });

  it("HTML-escapes item text so a malicious title can't inject markup", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ title: "<script>alert(1)</script>" })],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("renders a poster image with mandatory alt text and a formatted runtime for a movie", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [
        item({
          title: "A Movie",
          posterUrl: "https://example.com/poster.jpg",
          runtimeMinutes: 105,
          rating: { source: "tmdb", value: 7.8, scale: 10 },
        }),
      ],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).toContain('src="https://example.com/poster.jpg"');
    expect(html).toContain('alt="A Movie cover art"');
    expect(html).toContain("1h 45m");
    expect(html).toContain("7.8/10");
  });

  it("omits the poster image entirely when an item has no posterUrl", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item({ title: "No Poster Movie" })],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).not.toContain("<img");
    expect(html).toContain("No Poster Movie");
  });

  it("shows a book's page count and an audiobook's duration in the metadata line", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [
        item({ id: "2", externalId: "2", kind: "book", title: "A Book", pageCount: 320 }),
        item({
          id: "3",
          externalId: "3",
          kind: "audiobook",
          title: "An Audiobook",
          durationSeconds: 5400,
        }),
      ],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).toContain("320 pages");
    expect(html).toContain("1h 30m");
  });

  it("does not fall back to the old bare list markup", async () => {
    const html = await renderDefaultNewsletterHtml({
      newsletterName: "Weekly Digest",
      items: [item()],
      generatedAt: new Date("2026-01-20T00:00:00Z"),
    });

    expect(html).not.toContain("<ul ");
    expect(html).not.toContain("<ul>");
    expect(html).not.toContain("<li>");
    expect(html).toContain("<!doctype html");
  });
});
