import type { NewItem } from "@latestarr/adapter-core";
import Handlebars from "handlebars";

// A single hardcoded starter template for the Phase 2 MVP — the
// drag-and-drop GrapesJS builder replaces this in a later phase.
// {{title}}/{{subtitle}}/{{overview}} use Handlebars' default {{}}
// escaping, not {{{}}}, so item text from a source can't inject markup.
const TEMPLATE_SOURCE = `
<!doctype html>
<html>
  <body style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #222;">
    <h1 style="font-size: 20px;">{{newsletterName}}</h1>
    {{#if items.length}}
    <ul style="list-style: none; padding: 0; margin: 0;">
      {{#each items}}
      <li style="margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid #eee;">
        <strong>{{title}}</strong>
        {{#if subtitle}}<div style="color: #666; font-size: 14px;">{{subtitle}}</div>{{/if}}
        {{#if overview}}<p style="font-size: 14px;">{{overview}}</p>{{/if}}
        <div style="font-size: 12px; color: #999;">Added {{addedAtFormatted}}</div>
      </li>
      {{/each}}
    </ul>
    {{else}}
    <p>No new items in this period.</p>
    {{/if}}
    <footer style="font-size: 12px; color: #999; margin-top: 16px;">
      Generated by LatestArr on {{generatedAtFormatted}}
    </footer>
  </body>
</html>
`;

const compiledTemplate = Handlebars.compile(TEMPLATE_SOURCE);

interface RenderableItem {
  title: string;
  subtitle?: string;
  overview?: string;
  addedAtFormatted: string;
}

export interface NewsletterRenderContext {
  newsletterName: string;
  items: NewItem[];
  generatedAt: Date;
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function renderNewsletterHtml(context: NewsletterRenderContext): string {
  const items: RenderableItem[] = context.items.map((item) => ({
    title: item.title,
    subtitle: item.subtitle,
    overview: item.overview,
    addedAtFormatted: formatDate(item.addedAt),
  }));

  return compiledTemplate({
    newsletterName: context.newsletterName,
    items,
    generatedAtFormatted: formatDate(context.generatedAt),
  });
}
