// Generated by docs/assets/brand/generate.mjs; edit that script, not this file.
// The LatestArr stamp on a 64x64 grid. See docs/assets/brand/brand.md.
export const LOGO_FACE = {"x":12,"y":10,"size":40} as const;
export const LOGO_SHADOW_DROP = 3;
export const LOGO_HOLE_R = 2.4;
export const LOGO_HOLES: readonly (readonly [number, number])[] = [[12,10],[12,50],[52,10],[18.667,10],[18.667,50],[12,16.667],[52,16.667],[25.333,10],[25.333,50],[12,23.333],[52,23.333],[32,10],[32,50],[12,30],[52,30],[38.667,10],[38.667,50],[12,36.667],[52,36.667],[45.333,10],[45.333,50],[12,43.333],[52,43.333],[52,50]];
export const LOGO_L_PATH = "M22.8 18h9v13.8h11v9h-20Z";
export const LOGO_COLOURS = { tile: "#c31d4c", paper: "#ffffff", shadow: "#ef5d86", ink: "#c31d4c" } as const;
